CREATE TABLE IF NOT EXISTS "flatoinator3000_counters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flatoinator3000_counters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw',
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw' NOT NULL
);
--> statement-breakpoint
DROP TABLE "flatoinator3000_days";--> statement-breakpoint
ALTER TABLE "flatoinator3000_clicks" ADD COLUMN "user_id" integer NOT NULL;